### ISSUE TITLE
Fix the Top-Nav

### ISSUE THREAD

**Issue by MarcoMorawec** [sengngo/splurty#2]
Take a look at the wireframes in lesson 3 and compare that to your top-nav. You're contribute and about links are not lining up correctly and are pushed down one line.

I took a look at your top-nav code and it doesn't look like your columns are adding up properly to 12 columns. For review of how a grid system works, take a look at the grid system [here](http://getbootstrap.com/css/#grid). Also, there's one missing "dash" on line 30 of application.html.erb.

Make sure you always check your final product against the wireframes, so you know you've took care of everything.

Let me know once you fixed the top-nav, ok.

**Comment by sengngo** [comment]
I added the missing dash. I think I understand the grid system. Since it's a 12 column grid I need to have it add up to 12. For the size xs - I have col-xs-3 for the logo + hidden-xs (0 columns) + col-xs-7 and offset-2 which equals 12. 

I'll make note to check against wireframes.

**Comment by MarcoMorawec** [comment]
Nice job @sengngo :)
