### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by MarcoMorawec** [sengngo/splurty#3]
Ok last one - but getting feedback on your work, is what will help you become better.

Take a look at your logo - it's a red circle with blue text in it. It would look a lot better if the text where white.

Take a look at your CSS and see if you can change the color for the text inside of the logo.

**Comment by sengngo** [comment]
This is the CSS code I used to change the color and I changed the hover to a grey.
.logo {
    color: #fff;
}

**Comment by MarcoMorawec** [comment]
Nice job. 

Make sure you close this issue, now that you've completed it.
